# To use the MeowCop gem.
inherit_gem:
  meowcop:
    - config/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'

Rails:
  # If you use RuboCop with Ruby on Rails, turn on this option.
  Enabled: true

# You can customize rubocop settings.
# For example.
# Style/FrozenStringLiteralComment:
#   Enabled: true
#   EnforcedStyle: always
